stages:
  - deploy

deploy_develop:
  stage: deploy
  script:
    - ci/deploy_develop.sh
  only:
    - develop

deploy_stage:
  stage: deploy
  script:
    - chmod +x ci/deploy_stage.sh
    - ll
    - rm -rf react-hash-calendar
    - git clone git@127.0.0.1:HashTang/react-hash-calendar.git
    - cd react-hash-calendar
    - cnpm i
    - npm run build
    - cd build
    - ls
    - tar -zcvf calendar.tar.gz *
    - mv calendar.tar.gz /
  only:
    - master
